version: 2.1

orbs:
  cypress: cypress-io/cypress@2.0.0
  percy: percy/agent@0.1.3

executors:
  ci-node:
    docker:
      - image: cimg/node:16.14.0
    resource_class: large
    working_directory: /mnt/ramdisk
    environment:
      CYPRESS_INSTALL_BINARY: 0
  ci-cypress:
    docker:
      - image: 'cypress/included:10.8.0'
    resource_class: large
    working_directory: /mnt/ramdisk

jobs:
  cache-dependencies:
    parameters:
      key:
        type: string
    executor: ci-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - << parameters.key >>
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ./node_modules
          key: << parameters.key >>

workflows:
  commit-workflow:
    jobs:
      - cache-dependencies:
          key: v8-dependencies-cache-{{ checksum "yarn.lock" }}
      - cypress/run:
          command-prefix: npx percy exec --
          executor: ci-cypress
          browser: chrome
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          no-workspace: true