version: 2.1

orbs:
  percy: percy/agent@0.1.3

executors:
  ci-node:
    docker:
      - image: cimg/node:16.14.0
    resource_class: large
    working_directory: /mnt/ramdisk
    environment:
      CYPRESS_INSTALL_BINARY: 0
  ci-cypress:
    docker:
      - image: 'cypress/included:10.8.0'
    resource_class: large
    working_directory: /mnt/ramdisk

jobs:
  cache-dependencies:
    parameters:
      key:
        type: string
    executor: ci-node
    environment:
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - restore_cache:
          keys:
            - << parameters.key >>
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ./node_modules
          key: << parameters.key >>
  test-e2e:
    executor: ci-cypress
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies cache
          keys:
            - v8-dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run Cypress
          command: npx concurrently -k -s "command-cypress" -n "app,cypress" "yarn start" "npx wait-on http://localhost:3000 && yarn cypress:run --spec 'cypress/e2e/my-app.cy.ts'"

workflows:
  commit-workflow:
    jobs:
      - cache-dependencies:
          key: v8-dependencies-cache-{{ checksum "yarn.lock" }}
      - test-e2e:
          requires:
            - cache-dependencies